### ISSUE TITLE
duplicated notes after moved files

### ISSUE THREAD

**Issue by lovitus** [vrtmrz/obsidian-livesync#113]
1,moved files on `device A`, wait till sync completed.
2,open another `device B` , wait till sync completed
3,all the moved files still `exist in original place`, and also a `copy in the new folder`.

I use the latest version of obsidian and livesync plugin .
Thanks for your hard working

**Comment by cmuench** [comment]
I have the same issue.
Device A is a Linux Notebook (Obsidian installed via Flatpak)
Device B is a Android Smartphone

**Comment by vrtmrz** [comment]
Sorry for being late! I missed this!
It should have been fixed at 0.15.7. Could you please try the latest version?

**Comment by Vyeche** [comment]
Hi, thank you for the question. I've seen a similar behavior where it moves files but keeps them in the original location.

**Comment by vrtmrz** [comment]
Thank you for checking it out! I'm wondering about the behaviour.
The next time happens, could you please capture the log and `Pick a file to show history` and check the changeset of two files? (Both files, the original one and the new one).
The original one should be marked as `Deleted`.

**Comment by Vyeche** [comment]
Issue still occurring for me, see https://github.com/vrtmrz/obsidian-livesync/issues/133
