### ISSUE TITLE
Large file sync failed. only got a empty file (size of 0KB) on another machine.

### ISSUE THREAD

**Issue by sevenights** [vrtmrz/obsidian-livesync#160]
Thank you for the amazing sync plugin. I'm new to the livesync. When I test it, I found it might have problem with sync large file. 
I made two vaults on my mac, and built the couchdb following exactly [setup_own_server_cn.md](https://github.com/vrtmrz/obsidian-livesync/blob/main/docs/setup_own_server_cn.md) except changing the max_document_size from 50 000 000 to 5 000 000 000. The I configured the livesync on one vault, copy the uri and setup the uri on the other vault.
Then I tied to sync several large files, the results of file sync as follows. 

| id | file type | file size on the source vault | file size on the destination vault | 
| - | - | - | - |
| 1 | binary | 17MB | 17MB |
| 2 | binary | 400MB | 0KB |
| 3 | text | 300MB | 300MB |
| 4 | text | 400MB | 0KB |
| 5 | text | 600MB | 0KB |

It seems the livesync can create a file on the destination vault, but the content is empty.

I have run the `check database configuration` which seems no problem.
<img width="604" alt="image" src="https://user-images.githubusercontent.com/11865313/211845054-af631301-96e4-43f1-932a-63aa311a5603.png">

Where did I do wrong, or there is a limit of file size?

**Comment by vrtmrz** [comment]
Thank you for using this plugin and giving me grateful words! It is an honour for me!
However, I did not realise this issue, sorry for your inconvenience. You haven't lost your notes completely? I am worried about your note.

I think it will work fine if we set the `Chunk size` to around 50-250, or if it is not enough, we probably have to disable `Read chunks online`. 

If these configurations do not get things better, I will ask you to open the DevTools by `Option`+`Shift`+`i` and check any errors at the console pane and network pane.

P.S. If you don't mind my asking, what does a 400 MB text file look like? Do you make edits to this? LiveSync assumes text files will be modified, if it is not, we will be able to use a bit better method.

---

Explains

LiveSync does not store the note directly in the storage. The note will be split into metadata and many chunks.

To improve synchronising performance and use storage efficiency, the size of chunks is configured smaller initially. (IBM Cloudant also accepts only small chunks). However, large files are split into many chunks.

I assumed synchronising to the server would have been successful and at the synchronised device tries to collect chunks, it probably had failed. 
Synchronising to the server is performed in a robust way, but synchronising from the server is abridged about fetching chunks.

If we configured `Chunk size` to a larger number, there must be fewer numbers of chunks.
But it works for binary files. If our text file will also hard to collect chunks, we have to synchronise in a robust way at receiving too. This is "Disable `Read chunks online`".

**Comment by sevenights** [comment]
Thank you for such a fast response.

The livesync works fine with other files. So I didn't lose any note.

The large text file is a jsonl file, which is a dataset. You can assume it will not be modified.

The requirement for sync large file is because somehow I use obsidian in a file manage system way. So there are some large files.

About the DevTools, I don't how to open it. I pressed `shift` + `option` + `I` in obsidian, but nothing happend. Can you provide more information?

I wonder wether you test large file like more than 400MB?

# The reproduce steps:

Initial livesync on two vaults by click `Hatch - Discard`

Start the couchdb with command ` docker run --rm -it -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password -v /Users/abel/projects/couchdb/local.ini:/opt/couchdb/etc/local.ini -p 5984:5984 couchdb`

The local.ini as follows:
```ini
[couchdb]
single_node=true
max_document_size = 5000000000

[chttpd]
require_valid_user = true
max_http_request_size = 4294967296

[chttpd_auth]
require_valid_user = true
authentication_redirect = /_utils/session.html

[httpd]
WWW-Authenticate = Basic realm="couchdb"
enable_cors = true

[cors]
origins = app://obsidian.md,capacitor://localhost,http://localhost
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE
max_age = 3600
```

The files in the vault A:
```
large.bin  409MB
small bin.zip 82MB
test.txt  27B
```

The vault B is empty.

Config vault A to connect to the couchdb.

Remote Database configuration Connection Test and Check database configuration passed.

The livesync start to build the local database and asked for a `encrypt your setting` when I finished the set up wizard. 

And wait until the sync status showed Stopped icon.
![16735181057836](https://user-images.githubusercontent.com/11865313/212050302-8b5ad61b-6c78-467f-afcd-085cb13eacfe.jpg)


Then I checked the couchdb folder in the container `/opt/couchdb/`, which size is 160MB. It inferenced that the `small  bin.zip` had been upload to the server, but the `large.bin` not. At that moment, I had not changed the `chunk size` nor disabled the `read chunks online`.


Then I set the `chunk size` to 250 and disabled the `read chunks online`. This didn't seem to have an effect. The sync status was still.

![16735190479479](https://user-images.githubusercontent.com/11865313/212051727-8d70ec08-fbd2-4c06-819a-8e83c615a379.jpg)

I configured the vault B by coping URI and opening URI. And I got this.

![16735192028230](https://user-images.githubusercontent.com/11865313/212051764-d2d92477-76a0-4c66-9bfe-f634cdcd8b73.jpg)


Vault A is test-livesync, vault B is test-livesync2.

FYI, the report are below:
**vault A**
```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "5000000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 300
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
workingEncrypt: false
workingPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: false
disableRequestURI: false
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: t1
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 250
readChunksOnline: false
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
workingUseDynamicIterationCount: false
syncAfterMerge: true

```

**Vault B**
```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "5000000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 300
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
workingEncrypt: false
workingPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 250
batches_limit: 40
useHistory: false
disableRequestURI: false
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: t1
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 250
readChunksOnline: false
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
workingUseDynamicIterationCount: false
syncAfterMerge: true
```

**Comment by sevenights** [comment]
Well, I figured out the `DevTools` by searching through the issues... I dont know why the hotkey for it change to `command`+`option`+`i`.

I reproduced the problem. 
First I sync two vaults by command `replicate now` on both vaults, waiting the stopped icon appeared.
Then I cleared the console.
And I copied the large file `pytorch_model.bin` into vault A (test-livesync)，then run `replicate now`.
The output of console was:
<img width="748" alt="image" src="https://user-images.githubusercontent.com/11865313/212251648-072f9b83-8eba-4b34-aa7d-70551333e469.png">


Finally ran `replicate now` on the Vault B (test_livesync2)
The output of console was:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/11865313/212251337-62f9d71a-432c-4ed7-a4ec-279c0bb8aa9c.png">


The `Replication closed` appeared because I close the sync function by chosing `Disable all sync` in Presets for test.

**Comment by vrtmrz** [comment]
Thank you very much for the detailed information! 
It has been so helpful! And reproduced! 
There are several issues. Some of them are solved by configurations. (we have to keep chunk size lower, and probably we can not use read chunks online)
But the biggest problem is caused by file size as you said! 

Fortunately, the patch is smaller than I thought, but I didn’t test the behaviour much yet. I will test and release it in a few days!

**Comment by vrtmrz** [comment]
Thank you for your patience! v0.17.10 has been out now! 

Note: Recommended configurations are inside the release note. Memory usage will be large while processing larger files. It is highly recommended that you back up your vault before testing this.

**Comment by sevenights** [comment]
Thank you for your work and your quickly response and repair! 

But the minimum chunk size I can set is 100. Every time I set a value smaller than 100 and press `ESC` to exit configure window, It goes back to 100. It is OK I change it to a value larger than 100, such as 120, 200.

Even I reinstall the obsidian-livesync, I still have this problem.

I can disable `read chunks online`, set batch limit to 20 and set batch size to 80.

Below are some information.

```
----remote config----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  max_age: "3600"
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  authentication_redirect: /_utils/session.html
  hash_algorithms: sha256, sha
  require_valid_user: "true"
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "5000000000"
  single_node: "true"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---- Plug-in config ---
couchDB_URI: self-hosted
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: false
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 300
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: false
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
workingEncrypt: false
workingPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 80
batches_limit: 20
useHistory: false
disableRequestURI: false
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: t1
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 100
readChunksOnline: false
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
workingUseDynamicIterationCount: false
syncAfterMerge: true
```

Console output
```
test-livesync:2023/1/15 20:49:31->loading plugin
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:49:31->Self-hosted LiveSync v0.17.10 0.17.10 
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:31->Self-hosted LiveSync has undergone a major upgrade. Please open the setting dialog, and check the information pane.
2plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:31->Open Database...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:31->Database Info
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Database is now ready.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Database closed (by close)
2plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Open Database...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Database Info
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Database is now ready.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Initialize and checking database files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Updating database by new files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->UPDATE DATABASE
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->UPDATE DATABASE done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->UPDATE STORAGE
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->UPDATE STORAGE done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->CHECK FILE STATUS:0/3
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->CHECK FILE STATUS:0/3 done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Initialized, NOW TRACKING!
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:32->Oneshot Sync begin... (sync)
127.0.0.1:5984/test/_local/fpXPvz17LGt7YfLeafsYig%3D%3D?:1          Failed to load resource: the server responded with a status of 404 (Object Not Found)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:36->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:42->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:42->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:42->Replication stopped.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:42->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:49:42->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:50:06->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:06->Configuration has been flushed, please open it again
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:07->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:47->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:49->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:50->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:51->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:53->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:54->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:56->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:50:58->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:51:01->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:51:02->Replication closed
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:51:03->Error:Request failed, status 404
plugin:obsidian-livesync:6185 The above 404 is totally normal. PouchDB is just detecting if the remote exists.
2plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:51:04->Connected to test2
plugin:obsidian-livesync:19366 test-livesync:2023/1/15 20:51:05->{
  "cors": {
    "credentials": "true",
    "headers": "accept, authorization, content-type, origin, referer",
    "max_age": "3600",
    "methods": "GET, PUT, POST, HEAD, DELETE",
    "origins": "app://obsidian.md,capacitor://localhost,http://localhost"
  },
  "chttpd": {
    "bind_address": "any",
    "max_http_request_size": "4294967296",
    "port": "5984",
    "require_valid_user": "true"
  },
  "admins": {
    "admin": "-pbkdf2-03a199f609af69af50ff5e33293699a4363c002b,a5c86f2a912d93f9365e9b8580bdba76,10"
  },
  "vendor": {
    "name": "The Apache Software Foundation"
  },
  "feature_flags": {
    "partitioned||*": "true"
  },
  "chttpd_auth": {
    "authentication_redirect": "/_utils/session.html",
    "hash_algorithms": "sha256, sha",
    "require_valid_user": "true"
  },
  "indexers": {
    "couch_mrview": "true"
  },
  "prometheus": {
    "additional_port": "false",
    "bind_address": "127.0.0.1",
    "port": "17986"
  },
  "httpd": {
    "WWW-Authenticate": "Basic realm=\"couchdb\"",
    "bind_address": "127.0.0.1",
    "enable_cors": "true",
    "port": "5986"
  },
  "smoosh": {
    "state_dir": "./data"
  },
  "couch_httpd_auth": {
    "authentication_db": "_users"
  },
  "couchdb_engines": {
    "couch": "couch_bt_engine"
  },
  "couchdb": {
    "database_dir": "./data",
    "max_document_size": "5000000000",
    "single_node": "true",
    "uuid": "ba4bd516271d2da2ed8fb4197e41a293",
    "view_index_dir": "./data"
  }
}
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:10->Suffix has been changed. Reopening database...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:10->Database closed (by close)
2plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:10->Open Database...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:10->Database Info
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:10->Database is now ready.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->Initialize and checking database files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->Updating database by new files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->UPDATE DATABASE
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->UPDATE DATABASE done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->UPDATE STORAGE
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->UPDATE STORAGE done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->CHECK FILE STATUS:0/3
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->CHECK FILE STATUS:0/3 done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->Initialized, NOW TRACKING!
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:11->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:16->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:17->Synchronization setting configured as Periodic sync with batch database update.
2plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:17->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:17->Database closed for reset Database.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:17->Open Database...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:17->Database Info
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Database is now ready.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Local Database Reset
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Deleted!
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Database closed (by close)
2plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Open Database...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Database Info
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Database is now ready.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Initializing
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Database looks empty, save files as initial sync data
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Initialize and checking database files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->Updating database by new files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->UPDATE DATABASE
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->UPDATE DATABASE test.txt
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->UPDATE DATABASE small bin.zip
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:18->UPDATE DATABASE large2.bin
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:20->Content saved:test.txt ,chunks: 1 (new:1, skip:0, cache:0)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:23->DB <- STORAGE (plain) test.txt
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:24->Content saved:small bin.zip ,chunks: 11 (new:11, skip:0, cache:0)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:27->DB <- STORAGE (newnote) small bin.zip
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:27->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:40->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:43->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:43->Content saved:large2.bin ,chunks: 55 (new:55, skip:0, cache:0)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:47->DB <- STORAGE (newnote) large2.bin
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:47->UPDATE DATABASE done.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:47->Initialized, NOW TRACKING!
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:47->Initialize done!
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:48->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:48->All done! Please set up subsequent devices with 'Copy setup URI' and 'Open setup URI'.
4plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:48->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:48->Looking for the point last synchronized point.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:48->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:48->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:51->↑0 ↓2
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:52->Applying 1 files
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:51:52->Applied _design/replicate (1-0f40c216691697a537688d856e9ed75a) change...
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:02->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:02->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:02->Replication stopped.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:02->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:02->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:04->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:04->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:06->Setup URI copied to clipboard
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:08->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:09->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:37->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:37->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:37->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:40->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:45->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:45->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:45->Replication stopped.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:45->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:52:45->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:09->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:10->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:14->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:19->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:19->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:22->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:23->Replication is already in progress.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:26->Replication is already in progress.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:30->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:30->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:30->Replication stopped.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:30->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:30->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:31->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:41->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:41->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:44->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:53->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:54->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:53:55->Replication closed
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:13->Oneshot Sync begin... (sync)
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:13->Error:Request failed, status 404
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:16->Replication activated
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:21->Replication error
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:21->Error:Invalid string length
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:21->Replication stopped.
plugin:obsidian-livesync:19366 test-livesync-t1:2023/1/15 20:54:21->Replication error
```

**Comment by vrtmrz** [comment]
I appreciate your detailed log! 
This `Error:Invalid string length` indicates that the data which would be processed while in replication is still too large.

> But the minimum chunk size I can set is 100. Every time I set a value smaller than 100 and press ESC to exit configure window, It goes back to 100. It is OK I change it to a value larger than 100, such as 120, 200.

I am so surprised and really sorry about this. We could not configure `customChunkSize` now. I also have not realised this.
Fixed on v0.17.11. Now we can set it. 
(And probably we have to rebuild databases before synchronising once.)

And, `batch limit`would be a lower value. (30-50)
Could you please try the new version and use these values?
