### ISSUE TITLE
Some files have been left conflicted! Please resolve them by "Pick a file to resolve conflict".

### ISSUE THREAD

**Issue by cheng3969** [vrtmrz/obsidian-livesync#210]
Hi,
Im getting this when starting obsidian, but there is no CONFIG folder in my vault, i tried to overwrite remove database but still get this warning.
Please check logs below.

5/9/2023, 2:53:17 PM->UPDATE STORAGE done.
5/9/2023, 2:53:17 PM->CHECK FILE STATUS:0/66
5/9/2023, 2:53:17 PM->CHECK FILE STATUS:0/66 done.
5/9/2023, 2:53:17 PM->Initialized, NOW TRACKING!
5/9/2023, 2:53:17 PM->Some files have been left conflicted! Please resolve them by "Pick a file to resolve conflict". The list is written in the log.
5/9/2023, 2:53:17 PM->Conflicted: CONFIG/app.json.md
5/9/2023, 2:53:17 PM->Conflicted: CONFIG/appearance.json.md
5/9/2023, 2:53:17 PM->Conflicted: CONFIG/community-plugins.json.md
5/9/2023, 2:53:17 PM->Conflicted: CONFIG/core-plugins-migration.json.md
5/9/2023, 2:53:17 PM->Conflicted: CONFIG/core-plugins.json.md

**Comment by vrtmrz** [comment]
Hello, thank you for opening this issue! 
`CONFIG` is the pseudo directory name which used for plugin synchronisation, and as you mentioned, not exist on our vault.
However, the device name should be first (i.e. `iphone/CONFIG/app.json`).

Just to be sure, could you please make sure that all the devices to be synchronised have different names set?

**Comment by cheng3969** [comment]
Hi,
I set different names on my desktop and phone, then rebuild->fetch, and the issue is fixed.
Thank you for you help!

**Comment by jk278** [comment]
Hi, I'm having the same problem, I've been looking for a long time, please tell me exactly where to set the different names, I'd appreciate it.

**Comment by cheng3969** [comment]
![Screenshot 2023-05-11 164341](https://github.com/vrtmrz/obsidian-livesync/assets/36038316/e4fc1559-4661-4c0a-85b6-c2f7661079b9)
> Hi, I'm having the same problem, I've been looking for a long time, please tell me exactly where to set the different names, I'd appreciate it.

![rebuild->fetch](https://github.com/vrtmrz/obsidian-livesync/assets/36038316/5a3e6621-1525-440e-8ae9-f4e92642a68e)
![device names](https://github.com/vrtmrz/obsidian-livesync/assets/36038316/7ff8e332-195b-4327-8fc8-25d64f69ac38)

**Comment by jk278** [comment]
This helped me to solve the problem successfully, thank you for your reply.

**Comment by TheFiZi** [comment]
I never enabled Plugin Syncing and ran into this issue.

Following the steps in https://github.com/vrtmrz/obsidian-livesync/issues/210#issuecomment-1543590881 have not resolved the issue for me.

Now my Obsidian is complaining about conflicting CONFIG files from multiple devices.

I am not accessing my CouchDB with admin rights to the entire server, only admin rights to my specific database. Any chance that could be related?

**Comment by vrtmrz** [comment]
Sorry for being late! And, thank you all for following up with me while I was absent.
The way of configuring the device name is as @cheng3969 mentioned. Thank you so much.

However, I am worried about the case that happening without using plugin synchronising. It may be some issue.
May I ask about your configuration? It can be dumped by the `Make report` button on the `Hatch` pane. And verbose log might be helpful for us.

P.S. Without administration privileges, some features will not work, and rebuilding the database is one of them. Sorry for lacking documentation.

**Comment by vrtmrz** [comment]
Sorry for letting you all wait. (However, I have not caught the matter yet).
> I take it the process of rebuilding the database needs server admin because it drops/recreates the database instead of truncating the databases contents and leaving the database in place?

Yes, this is correct. 
> Would it be worth me creating a separate feature request that all database related processes be reviewed and modified (if possible) so they can be performed with only admin access to a database and not the entire server? I have to imagine this is possible and I'm not the only one that wants to create a CouchDB Docker Container for each user. If this is outside of the scope of the plugin that's cool to and I'll drop it :)

It might be a fine and correct way. However, the administrator would be harried about accepting inquiries.
The way I have chosen to build the tasting server;  just limiting every our own access only to our own named database. (Except administrator). For example, If we were `user1`, only accessible to `http://example.com/user1-somedatabase` or `http://example.com/user1-anotherdatabase`. It can be configured by reverse proxy. Just for your information, I wrote a configuration sample of a user-filtering proxy for Nginx, similar to the one used on the Tasting server. 
I hope that this will help you.

```
server {
    # snipped non-related configuration...
    set $api_backend "couchdb-proxied:5984"; 

    location / {
        # To return the database information.
        location = / {
            proxy_pass http://${api_backend}/;
            break;
        }
        # For replication.
        location ~ ^/_session {
             proxy_pass http://${api_backend};
        }
        # A user is only able to access the database which is prefixed with their name-.
        location ~  ^/([^_][^/-]*)-(.*)$ {
            if ($remote_user != $1) {
                # To make 404 error with checking access rights.
                proxy_pass http://${api_backend}/_an_forbidden_something;
            }
            # Proxy to the database. 
            proxy_pass http://${api_backend};
        }
        # Fauxton can be opened with example.com/admin/_utils.
        # Please change `admin` as you like. It may be too easy and dangerous to leave it as it is.
        location ~ ^/admin/(.*)$ {
            if ($remote_user != "admin") {
                proxy_pass http://${api_backend}/_an_forbidden_something;
            }
            rewrite  /admin/(.*)$  /$1 break;
            proxy_pass http://${api_backend};
        }
        # Other everything will be handled here.
        return 401;
    }
}
```

**Comment by TheFiZi** [comment]
@vrtmrz Thank you for the explanation and nginx example. I've re-configured my couchdb and was able to resolve my sync warnings with the instructions posted here: https://github.com/vrtmrz/obsidian-livesync/issues/210#issuecomment-1543590881

**Comment by vrtmrz** [comment]
I am very relieved to hear that!
