### ISSUE TITLE
Sync fails with Decryption with HKDF failed. on Path

### ISSUE THREAD

**Issue by regul42** [vrtmrz/obsidian-livesync#686]
Thank you for taking the time to report this issue!
To improve the process, I would like to ask you to let me know the information in advance.

All instructions and examples, and empty entries can be deleted.
Just for your information, a [filled example](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Issue+example) is also written.

## Abstract
Sync on laptop stopped working with a decryption error and repeating "Fetched synchronisation parameters" 

## Expected behaviour
- Working sync

## Actually happened
- Setup livesync on a linux laptop, Android phone and iPad.
- Sync worked initially.
- Yesterday the sync worked great between iPad and Android.
- Sync still seems to work on Android.
- Laptop and iPad now present this error since today.
- This error is also present when configuring the connection with a new empty vault.

## Reproducing procedure

1. 

Note: If you do not catch the reproducing procedure, please let me know the frequency and signs.

## Report materials
If the information is not available, do not hesitate to report it as it is. You can also of course omit it if you think this is indeed unnecessary. If it is necessary, I will ask you.

### Report from the LiveSync
For more information, please refer to [Making the report](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Making+the+report).
<details>
<summary>Report from hatch</summary>

```
# ---- Obsidian info ----
navigator: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.8.10 Chrome/132.0.6834.196 Electron/34.2.0 Safari/537.36
fileSystem: sensitive

---
# ---- remote config ----
cors:
  credentials: "true"
  headers: accept, authorization, content-type, origin, referer
  methods: GET, PUT, POST, HEAD, DELETE
  origins: app://obsidian.md,capacitor://localhost,http://localhost
chttpd:
  bind_address: any
  enable_cors: "true"
  max_http_request_size: "4294967296"
  port: "5984"
  require_valid_user: "true"
admins: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
vendor:
  name: The Apache Software Foundation
nouveau:
  url: http://127.0.0.1:5987
feature_flags:
  partitioned||*: "true"
chttpd_auth:
  hash_algorithms: sha256, sha
  require_valid_user: "true"
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
indexers:
  couch_mrview: "true"
prometheus:
  additional_port: "false"
  bind_address: 127.0.0.1
  port: "17986"
httpd:
  WWW-Authenticate: Basic realm="couchdb"
  bind_address: 127.0.0.1
  enable_cors: "true"
  port: "5986"
smoosh:
  state_dir: ./data
couch_httpd_auth:
  authentication_db: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  secret: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  authentication_redirect: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchdb_engines:
  couch: couch_bt_engine
couchdb:
  database_dir: ./data
  max_document_size: "50000000"
  uuid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
  view_index_dir: ./data

---
# ---- Plug-in config ----
version: 0.25.3
remoteType: ""
useCustomRequestHandler: false
couchDB_URI: self-hosted(HTTPS)
couchDB_USER: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_PASSWORD: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
couchDB_DBNAME: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
liveSync: false
syncOnSave: true
syncOnStart: true
savingDelay: 200
lessInformationInLog: false
gcDelay: 0
versionUpFlash: ""
minimumChunkSize: 20
longLineThreshold: 250
showVerboseLog: false
suspendFileWatching: false
trashInsteadDelete: true
periodicReplication: true
periodicReplicationInterval: 60
syncOnFileOpen: true
encrypt: true
passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
usePathObfuscation: true
doNotDeleteFolder: false
resolveConflictsByNewerFile: false
batchSave: true
batchSaveMinimumDelay: 5
batchSaveMaximumDelay: 60
deviceAndVaultName: ""
usePluginSettings: false
showOwnPlugins: false
showStatusOnEditor: true
showStatusOnStatusbar: true
showOnlyIconsOnEditor: false
hideFileWarningNotice: false
usePluginSync: false
autoSweepPlugins: false
autoSweepPluginsPeriodic: false
notifyPluginOrSettingUpdated: false
checkIntegrityOnSave: false
batch_size: 50
batches_limit: 50
useHistory: true
disableRequestURI: true
skipOlderFilesOnSync: true
checkConflictOnlyOnOpen: false
showMergeDialogOnlyOnActive: false
syncInternalFiles: false
syncInternalFilesBeforeReplication: false
syncInternalFilesIgnorePatterns: \/node_modules\/, \/\.git\/, \/obsidian-livesync\/
syncInternalFilesTargetPatterns: ""
syncInternalFilesInterval: 60
additionalSuffixOfDatabaseName: c34a42839bc8db24
ignoreVersionCheck: false
lastReadUpdates: 0
deleteMetadataOfDeletedFiles: false
syncIgnoreRegEx: ""
syncOnlyRegEx: ""
customChunkSize: 60
readChunksOnline: true
watchInternalFileChanges: true
automaticallyDeleteMetadataOfDeletedFiles: 0
disableMarkdownAutoMerge: false
writeDocumentsIfConflicted: false
useDynamicIterationCount: false
syncAfterMerge: false
configPassphraseStore: ""
encryptedPassphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
encryptedCouchDBConnection: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
permitEmptyPassphrase: false
useIndexedDBAdapter: true
useTimeouts: false
writeLogToTheFile: false
doNotPaceReplication: false
hashCacheMaxCount: 300
hashCacheMaxAmount: 50
concurrencyOfReadChunksOnline: 100
minimumIntervalOfReadChunksOnline: 100
hashAlg: xxhash64
suspendParseReplicationResult: false
doNotSuspendOnFetching: false
useIgnoreFiles: false
ignoreFiles: .gitignore
syncOnEditorSave: false
pluginSyncExtendedSetting: {}
syncMaxSizeInMB: 50
settingSyncFile: ""
writeCredentialsForSettingSync: false
notifyAllSettingSyncFile: false
isConfigured: true
settingVersion: 10
enableCompression: false
accessKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
bucket: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
endpoint: Not configured or AWS
region: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(4 letters)
secretKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷
useEden: false
maxChunksInEden: 10
maxTotalLengthInEden: 1024
maxAgeInEden: 10
disableCheckingConfigMismatch: false
displayLanguage: def
enableChunkSplitterV2: false
disableWorkerForGeneratingChunks: false
processSmallFilesInUIThread: false
notifyThresholdOfRemoteStorageSize: 800
usePluginSyncV2: true
usePluginEtc: false
handleFilenameCaseSensitive: false
doNotUseFixedRevisionForChunks: true
showLongerLogInsideEditor: false
sendChunksBulk: false
sendChunksBulkMaxSize: 1
useSegmenter: false
useAdvancedMode: false
usePowerUserMode: false
useEdgeCaseMode: false
enableDebugTools: false
suppressNotifyHiddenFilesChange: false
syncMinimumInterval: 2000
P2P_Enabled: false
P2P_AutoAccepting: 0
P2P_AppID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(20 letters)
P2P_roomID: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_passphrase: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
P2P_relays: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(27 letters)
P2P_AutoBroadcast: false
P2P_AutoStart: false
P2P_AutoSyncPeers: ""
P2P_AutoWatchPeers: ""
P2P_SyncOnReplication: ""
P2P_RebuildFrom: ""
P2P_AutoAcceptingPeers: ""
P2P_AutoDenyingPeers: ""
P2P_IsHeadless: false
doctorProcessedVersion: 0.25.0
bucketCustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
couchDB_CustomHeaders: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
useJWT: false
jwtAlgorithm: ""
jwtKey: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtKid: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtSub: 𝑅𝐸𝐷𝐴𝐶𝑇𝐸𝐷(0 letters)
jwtExpDuration: 5
useRequestAPI: false
bucketPrefix: ""
chunkSplitterVersion: v3-rabin-karp
E2EEAlgorithm: v2

```
</details>

### Obsidian debug info
<details>
<summary>Debug info</summary>

```
<!-- paste here -->
```
</details>

### Plug-in log
We can see the log by tapping the Document box icon. If you noticed something suspicious, please let me know.
Note: **Please enable `Verbose Log`**. For detail, refer to [Logging](https://docs.vrtmrz.net/LiveSync/hintandtrivia/Logging), please.

<details>
<summary>Plug-in log</summary>

```
28/07/2025, 12:20:32->[ModuleLiveSyncMain]  Loading plugin...
28/07/2025, 12:20:32->[ModuleLiveSyncMain]  Self-hosted LiveSync v0.25.3 0.25.3
28/07/2025, 12:20:32->[HiddenFileSync]  Hidden file will skip 0 files
28/07/2025, 12:20:32->LiveSync has updated, please read the changelog!
28/07/2025, 12:20:32->[ModuleLocalDatabaseObsidian]  Waiting for ready...
28/07/2025, 12:20:32->Opening Database...
28/07/2025, 12:20:32->Database is now ready.
28/07/2025, 12:20:32->Log window opened
28/07/2025, 12:20:33->[ModuleInitializerFile]  Initialize and checking database files
28/07/2025, 12:20:33->[ModuleInitializerFile]  Checking deleted files
28/07/2025, 12:20:33->[ModuleInitializerFile]  Collecting local files on the DB: 25
28/07/2025, 12:20:33->[ModuleInitializerFile]  Collecting local files on the DB: 50
28/07/2025, 12:20:33->[ModuleInitializerFile]  Collecting local files on the DB: 75
28/07/2025, 12:20:33->[ModuleInitializerFile]  Synchronising...
28/07/2025, 12:20:33->[ModuleInitializerFile]  UPDATE DATABASE: Nothing to do
28/07/2025, 12:20:33->[ModuleInitializerFile]  UPDATE STORAGE
28/07/2025, 12:20:33->[ModuleInitializerFile]  SYNC DATABASE AND STORAGE
28/07/2025, 12:20:33->[ModuleInitializerFile]  UPDATE STORAGE: DONE:1, FAILED:0, LAST:42
28/07/2025, 12:20:33->[ModuleInitializerFile]  Initialized, NOW TRACKING!
28/07/2025, 12:20:33->Rule satisfied: sendChunksBulk is false
28/07/2025, 12:20:33->Rule satisfied: sendChunksBulkMaxSize is 1
28/07/2025, 12:20:33->Rule satisfied: doNotUseFixedRevisionForChunks is true
28/07/2025, 12:20:33->Rule satisfied: handleFilenameCaseSensitive is false
28/07/2025, 12:20:33->Rule satisfied: useIndexedDBAdapter is true
28/07/2025, 12:20:33->Rule satisfied: useEden is false
28/07/2025, 12:20:33->Rule satisfied: hashAlg is xxhash64
28/07/2025, 12:20:33->Rule satisfied: disableCheckingConfigMismatch is false
28/07/2025, 12:20:33->Rule satisfied: enableCompression is false
28/07/2025, 12:20:33->Rule satisfied: usePluginSyncV2 is true
28/07/2025, 12:20:33->Rule satisfied: chunkSplitterVersion is v3-rabin-karp
28/07/2025, 12:20:33->Rule satisfied: customChunkSize is 60
28/07/2025, 12:20:33->Rule satisfied: E2EEAlgorithm is v2
28/07/2025, 12:20:33->[ModuleInitializerFile]  UPDATE STORAGE: DONE:1, FAILED:0, LAST:42
SYNC DATABASE AND STORAGE All done: DONE:43, FAILED:0
28/07/2025, 12:20:33->Fetched synchronisation parameters
28/07/2025, 12:20:33->OneShot Sync begin... (sync)
28/07/2025, 12:20:33->[ModuleCheckRemoteSize]  Remote storage size: 2.16MB
28/07/2025, 12:20:33->Replication activated
28/07/2025, 12:20:33->Fetched synchronisation parameters
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:20:34->Decryption with HKDF failed. on Path
28/07/2025, 12:20:34->OperationError:
28/07/2025, 12:21:33->Fetched synchronisation parameters
28/07/2025, 12:22:33->Fetched synchronisation parameters
28/07/2025, 12:23:33->Fetched synchronisation parameters
28/07/2025, 12:24:33->Fetched synchronisation parameters

28/07/2025, 13:33:33->Rule satisfied: sendChunksBulk is false
28/07/2025, 13:33:33->Rule satisfied: sendChunksBulkMaxSize is 1
28/07/2025, 13:33:33->Rule satisfied: doNotUseFixedRevisionForChunks is true
28/07/2025, 13:33:33->Rule satisfied: handleFilenameCaseSensitive is false
28/07/2025, 13:33:33->Rule satisfied: useIndexedDBAdapter is true
28/07/2025, 13:33:33->Rule satisfied: useEden is false
28/07/2025, 13:33:33->Rule satisfied: hashAlg is xxhash64
28/07/2025, 13:33:33->Rule satisfied: disableCheckingConfigMismatch is false
28/07/2025, 13:33:33->Rule satisfied: enableCompression is false
28/07/2025, 13:33:33->Rule satisfied: usePluginSyncV2 is true
28/07/2025, 13:33:33->Rule satisfied: chunkSplitterVersion is v3-rabin-karp
28/07/2025, 13:33:33->Rule satisfied: customChunkSize is 60
28/07/2025, 13:33:33->Rule satisfied: E2EEAlgorithm is v2
28/07/2025, 13:33:33->No issues found but marked as to be silent
28/07/2025, 13:33:33->Cache initialized 300 / 50000000
28/07/2025, 13:33:33->[ModuleLiveSyncMain]  Additional safety scan...
28/07/2025, 13:33:33->[ModuleInteractiveConflictResolver]  Checking conflicted files
28/07/2025, 13:33:33->[ModuleInitializerFile]  UPDATE STORAGE: DONE:1, FAILED:0, LAST:42
SYNC DATABASE AND STORAGE All done: DONE:43, FAILED:0
28/07/2025, 13:33:33->[ModuleInteractiveConflictResolver]  There are no conflicting files
28/07/2025, 13:33:33->[ModuleCheckRemoteSize]  Checking storage sizes
28/07/2025, 13:33:33->Fetched synchronisation parameters
28/07/2025, 13:33:33->No changes in synchronisation parameters after fetch
28/07/2025, 13:33:33->PBKDF2 salt for replication: removed
28/07/2025, 13:33:33->OneShot Sync begin... (sync)
28/07/2025, 13:33:33->[ModuleCheckRemoteSize]  Remote storage size: 2.24MB
28/07/2025, 13:33:33->[ModuleLiveSyncMain]  Additional safety scan completed
28/07/2025, 13:33:33->Replication paused
28/07/2025, 13:33:33->Replication activated
28/07/2025, 13:33:34->Fetched synchronisation parameters
28/07/2025, 13:33:34->No changes in synchronisation parameters after fetch
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:34->Decryption with HKDF failed. on Path
28/07/2025, 13:33:34->OperationError:
28/07/2025, 13:33:38->PBKDF2 salt for replication: removed
28/07/2025, 13:33:38->Fetched synchronisation parameters
28/07/2025, 13:33:38->No changes in synchronisation parameters after fetch
28/07/2025, 13:33:38->PBKDF2 salt for replication: 1removed

iPad has a little more info:
OperationError:The operation failed for an operation-specific reason
```
</details>

### Network log
Network logs displayed in DevTools will possibly help with connection-related issues. To capture that, please refer to [DevTools](https://docs.vrtmrz.net/LiveSync/hintandtrivia/DevTools).

### Screenshots
If applicable, please add screenshots to help explain your problem.

### Other information, insights and intuition.
Please provide any additional context or information about the problem.

**Comment by regul42** [comment]
@vrtmrz Thanks for your reply!
I have just started with Obsidian and your add-on, so I'm not to invested yet.

I have rebuild the remote database from my laptop (the rebuilding options are under Maintenance instead of Hatch) and got notifications on my phone and tablet to fetch the remote database. 
After that I unlocked the database, set all sync to LiveSync and it works again.

Thanks for your quick reply and take it easy! I'll keep an eye on this to see if I can help in some way.
Thanks for this plugin!

**Comment by ccharname** [comment]
me too, same problem.
2025/7/29 17:13:37->Decryption with HKDF failed. on Path
2025/7/29 17:13:37->OperationError:

**Comment by michaelmm** [comment]
I have the same issue as well, it was working fine yesterday. Now getting the "Decryption with HKDF failed. on Path" on both Android and Mac clients. My setup is Self-hosted LiveSync->CouchDB Container (ubuntu 24)

**Comment by vrtmrz** [comment]
Sorry for the delay in notifying you of the new release! (As usual, my excuses are detailed; you can read the bold text first).

**Self-hosted LiveSync v0.25.4 that fixes this issue has been released!**

This issue had been caused by a mixture of different Security-Seeds (previously called 'PBKDF2 salt', but too technical a term). They (probably, at least I have detected) have been created due to a connection error or an offline error. Misdetection of errors as 'Not Found' causes the (re-)generation of a new Security Seed.

And, more unfortunately, that Security-Seeds were cached on previous versions. Hence, it means that some data on our remote database would be encrypted with keys that cannot able to be decrypted (it means no exposure, but the problem). It had only occurred on the remote database, and our local databases on devices are sane. That because any synchronisation had been prevented. Sorry for the inconvenience, but the safety-conscious design (indeed, a bit ironic, and sometimes against, but) saved us.

**So, we have to re-encrypt the remote database with the correct and single key with the Security-Seed. We can perform this by a `Maintenance`-> `Rebuilding Operation` -> `Overwrite remote` -> `Send` to overwrite the remote.**
As usual, this will take some time. Please perform it from a stable device with a stable network connection. However, we do not need to fetch the remote database again on the other devices. The remote database is overwritten by the correct keys. Nothing changed essentially. And we are always performing 'Replication'; with all your efforts (I know that the configuration is a bit difficult, and we have to resolve configuration mismatches always. But it surely works for our tranquillity and system robustness).


**Therefore, we only have to `Unlock` the database lockout after the overwriting, from other devices (you will see the dialogue).**
**However, indeed corrupted once, please back your vault up surely.**


And since v0.25.4, no longer unverified Security-Seeds will be used, and overwriting this will be detected more robustly.

May I ask you to check the behaviour of the latest version with database-overwriting, please?

**Comment by michaelmm** [comment]
Sync working, thanks for the quick turnaround fix!

**Comment by regul42** [comment]
Updated on laptop, followed by phone and tablet. 
Sync works.

If everything was working is it needed to do the "Overwrite remote" and "Unlock database" actions?

**Comment by Greyswandir-gg** [comment]
@vrtmrz 
Do I understand correctly that this also applies to this issue? After updating the plugin (today), I've been trying to fix this error all day. I've tried literally everything. Everything was preserved on the phone and tablet as before the update, and it seems that even when I updated the plugin there, nothing changed.
I've been racking my brain all day on how to solve the situation.

<img width="342" height="224" alt="Image" src="https://github.com/user-attachments/assets/f81f6833-0ffb-4dea-8680-168bd4d8a398" />

**Comment by AlexsdeG** [comment]
Update: I found workaround. After multi retries I think the issue is maybe with a corupted couchdb or livesync plugin in my old Vault. Fortunatly I got it to run. I backuped my old Vault. Created a new Vault and copied all folders and files (except .obsidian) to the new vault. Than i downloaded the livesync plugin and set it up manualy with a new database name but same url, un and pw. After setting up i created a setup uri which i used on my other devices original vault to add them to the sync. After making sure sync is working i copied all other files form .obsidian folder into my new vault but for the plugins i made sure to copy all plugins except livesync

**Comment by Hellothink-ca** [comment]
On May, 2026 this problem is still there. Version version 1.12.7(303) obsidian.
It happen when I was adding a third ios device to the server.
This third ios device has not set anything and only turned on customization and hidden file sync. 
When this happens, what is happening at the same time is that, laptop and ios device could not sync to each other.
But the ios devices seems to sync.

**Comment by 917huB** [comment]
I’m seeing this problem frequently with 0.25.62 still. 
One iPhone and one MacBook. It’s unreliable and frequent enough that I can’t rely on it. 
Happy to help troubleshoot however I can support.

**Comment by vrtmrz** [comment]
Sorry for the delay, everyone.
I am afraid I have to apologise again, but as this logic is occasionally updated, there may be another reason for this.
I am terribly sorry to ask, but could you please describe how it behaves in the latest version and provide a report?

You are welcome to open a new issue; Would you mind if I asked you to create one using the new issue template and attach a full report? You can generate a full report from the Command Palette.

I really do not wish to waste all your efforts, but please allow me to be so bold as to close this issue to move to the brand new investigation.
